(ns suji.methods.analyze-test
  "The report `analyze` renders is the only user-facing artefact this library has,
  and until now it had NO test at all — `grep -rn render-report test/` returned
  nothing.

  It did not merely go unchecked; it was BROKEN. `clojure -M -m suji.methods.analyze`
  — the command the README gives under its headline table — exited 1 with a
  NullPointerException, because two `fmt-f` calls in the muscle table were handed
  a nil `:mvc-pct`. Twelve of the forty-eight rows have one at the default posture:
  the two ligaments, which cannot contract and so have no maximum voluntary
  contraction to be a fraction of, and ten antagonists the solver refused.

  Every sibling in the same file already handled it — `worst-stiffness` filters,
  the sort puts nil last, `stiffness-band` has its own band, the endurance `cond`
  has a nil case. Only the two format calls did not, and no test rendered the
  report, so the README's own headline table could not be regenerated by the
  command the README gives."
  (:require [clojure.string :as str]
            [clojure.test :refer [deftest is]]
            [suji.methods.analyze :as analyze]
            [suji.methods.muscle :as muscle]))

(defn- report []
  (analyze/render-report (analyze/analyze-all) 120.0))

(deftest the-report-renders-at-all
  ;; The regression proper. Before the fix this threw rather than returning.
  (let [r (report)]
    (is (string? r))
    (is (< 100 (count (str/split-lines r)))
        "a report this short is not the report")))

(deftest every-strain-row-reaches-the-report
  ;; A row that throws is loud; a row silently dropped is not, and the fix could
  ;; have been written that way (skip the nils and move on). Assert instead that
  ;; the count of muscle-table rows matches the count of strains computed.
  (let [results (analyze/analyze-all)
        r (analyze/render-report results 120.0)
        want (count (:strains (first results)))
        ;; the first workstation's table: rows between its header and the blank
        ;; line that ends it
        got (->> (str/split-lines r)
                 (drop-while #(not (str/starts-with? % "| muscle |")))
                 rest rest
                 (take-while #(str/starts-with? % "|"))
                 count)]
    (is (pos? want) "no strains were computed, so this asserts nothing")
    (is (= want got)
        (str "computed " want " strains but rendered " got " rows"))))

(deftest a-row-without-a-mvc-is-rendered-as-a-refusal-with-its-reason
  ;; Not as a dash. A dash in the %MVC column reads as a small number; the reason
  ;; is the answer. And the branch must be on whether the number exists, not on
  ;; `:refused` — a ligament has no %MVC and was never refused.
  (let [results (analyze/analyze-all)
        strains (:strains (first results))
        without (remove muscle/numeric-mvc? strains)
        r (analyze/render-report results 120.0)]
    (is (seq without) "the default posture must contain rows without a %MVC")
    (doseq [s without]
      (let [row (first (filter #(str/starts-with? % (str "| " (:name s) " |"))
                               (str/split-lines r)))]
        (is (some? row) (str "no row rendered for " (:name s)))
        (is (str/includes? (or row "") "適用範囲外")
            (str "not marked out of range: " row))))
    ;; both reasons must survive as themselves — a ligament having no %MVC and the
    ;; solver refusing a muscle are different answers
    (is (str/includes? r "no-mvc") "a ligament's reason was collapsed")
    (is (str/includes? r "acts-the-wrong-way") "a refusal's reason was collapsed")))

(deftest rows-with-a-mvc-still-show-one
  ;; The control. Without it every assertion above would also be satisfied by a
  ;; report that marked EVERY row out of range.
  (let [results (analyze/analyze-all)
        strains (:strains (first results))
        with (filter muscle/numeric-mvc? strains)
        r (analyze/render-report results 120.0)]
    (is (seq with) "no row has a %MVC, so this asserts nothing")
    (doseq [s (take 5 with)]
      (let [row (first (filter #(str/starts-with? % (str "| " (:name s) " |"))
                               (str/split-lines r)))]
        (is (not (str/includes? (or row "") "適用範囲外"))
            (str "a row with a %MVC was marked out of range: " row))))))

(deftest an-infinite-endurance-says-it-is-the-models-floor
  ;; `∞` alone reads as a measured result. Below 8 %MVC it is the model's own
  ;; floor — `strain` computes the position and the report used to drop it.
  (let [results (analyze/analyze-all)
        strains (:strains (first results))
        floored (filter #(= :below-endurance-floor (:endurance-position %)) strains)
        r (analyze/render-report results 120.0)]
    (is (seq floored) "no row sits below the floor, so this asserts nothing")
    (doseq [s (take 3 floored)]
      (let [row (first (filter #(str/starts-with? % (str "| " (:name s) " |"))
                               (str/split-lines r)))]
        (is (str/includes? (or row "") "床未満")
            (str "an unbounded endurance was shown unqualified: " row))))))

(deftest the-report-carries-its-non-diagnostic-boundary
  ;; Charter (G1, 医師法 §17), asserted on the surface a person actually reads.
  ;;
  ;; Stated as a POSITIVE: the disclaimer must be present. I first wrote this as a
  ;; ban on clinical words, and it failed immediately on `NON-DIAGNOSTIC` and on
  ;; the sentence saying the report is not treatment — that is, it flagged the very
  ;; text that exists to state the boundary. A word ban cannot tell a claim from a
  ;; disclaimer, and the repo already has `charter_invariants_test` for the
  ;; vocabulary. What was missing here was only that the rendered report says so.
  (let [r (report)]
    (is (str/includes? r "NON-DIAGNOSTIC")
        "the rendered report does not state that it is non-diagnostic")
    (is (str/includes? r "医師法")
        "the rendered report does not name the statute it is bounded by")))
